export const MINUTES_PER_HOUR = 60;
export const HOURS_PER_DAY = 24;
export const MINUTES_PER_DAY = HOURS_PER_DAY * MINUTES_PER_HOUR;

export const SLEEP_CYCLE_MINUTES = 90;

export const FOUR_SLEEP_CYCLES = 4 * SLEEP_CYCLE_MINUTES;
export const FIVE_SLEEP_CYCLES = 5 * SLEEP_CYCLE_MINUTES;
export const SIX_SLEEP_CYCLES = 6 * SLEEP_CYCLE_MINUTES;
